### PR TITLE
JSON to AVRO conversion from Camus

### PR DESCRIPTION
**Pull request by santosh-d3vpl3x**
Duplicate of : https://github.com/linkedin/camus/issues/195
Hi there

Camus should be able to consume JSON messages and convert them into the AVRO with the help schema in schema repository. I have forked the master and made changes to cater this requirements. 

I would like to submit merge request for the same. Please have a look at codebase at https://github.com/santosh-d3vpl3x/camus

Class which acts as converter is, [JSONToAvroMessageDecoder.java](https://github.com/santosh-d3vpl3x/camus/blob/master/camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/JSONToAvroMessageDecoder.java)

### CODE REVIEW

**Comment by zliu41** [comment]
Hi @santosh-d3vpl3x !
We recently added a `com.linkedin.camus.coders.Message` class. Please have your new class extend `MessageDecoder<Message, GenericData.Record>` instead of `MessageDecoder<byte[], GenericData.Record>`. 

Thanks
-Ziyang

**Comment by santosh-d3vpl3x** [comment]
Done!

**Comment by zliu41** [comment]
LGTM. Thanks.

**Comment by santosh-d3vpl3x** [comment]
I will document the code ASAP.

**Pull request merged**
