### PR TITLE
Allow s3 as possible output for destination and execution dirs

### PR DESCRIPTION
**Pull request by kevinsu**
allow s3 as a possible output dir for etl.destination.path, etl.execution.base.path, etl.execution.history.path.

Did this by changing the relevant FileSystem.get(conf) calls to FileSystem.get(uri, conf).  

Could use some direction on whether this is actually ok to do, and how to proceed with writing tests and such.  As it is, I'm using it to output stuff to s3 myself.  

Edit:  The reason I did this was because I was unable to get the fs.defaultFS or fs.default.name options working.  

I think a second reason, even if the fs.defaultFS stuff did work, is that this way, we are still doing the work in the local fs (hdfs for emr) and then copying data to s3, vs doing all the work in s3.  Thanks @bcotton!

### CODE REVIEW

**Comment by bcotton** [comment]
FWIW, we've been using S3 and Camus for a while. We just set these in the properties file:

fs.default.name=s3://<bucket>
fs.defaultFS=s3://<bucket>

**Comment by kevinsu** [comment]
I found that that did not work when using it on EMR.  I would get this error 

Exception in thread "main" java.io.IOException: Cannot initialize Cluster. Please check your configuration for mapreduce.framework.name and the correspond server addresses.

Perhaps caused by this:
2015-04-22 17:36:34,708 INFO org.apache.hadoop.mapreduce.Cluster (main): Failed to use org.apache.hadoop.mapred.YarnClientProtocolProvider due to error: Error in instantiating YarnClient

**Comment by bcotton** [comment]
Could be. We are still running on Hadoop 1 in EMR.

**Comment by kfleischmann** [comment]
Hey guys. i face the same Problem. How is the fix?

**Pull request closed without merging**
